/**
 * Represents the scale calibration settings for translating 2D canvas pixels 
 * to real-world imperial or metric construction dimensions.
 */
export interface BlueprintScale {
  /** The length of the calibration line drawn on screen (in pixels) */
  pixelLength: number;
  /** The physical, real-world equivalent length (e.g., 30.0) */
  realWorldLength: number;
  /** The unit of measurement for this sheet's drawings */
  unit: 'ft' | 'in' | 'm' | 'cm';
  /** Calculated scale ratio: pixels per unit of measurement (px/ft) */
  scaleFactor: number;
  /** Flag showing if the estimator has manually calibrated this sheet */
  isCalibrated: boolean;
}

/**
 * Metadata for individual pages extracted from an uploaded architectural PDF document.
 */
export interface BlueprintPage {
  id: string;
  blueprintId: string;
  pageNumber: number;
  /** Label/title extracted from the PDF sheet title block (e.g., "FOUNDATION PLAN") */
  title?: string;
  /** Dimension properties of the PDF viewport box at native scale */
  width: number;
  height: number;
  /** URL pointing to the rendered page background image (stored in cloud storage) */
  imageUrl: string;
  /** Optional low-res image URL used for sidebar preview cards */
  thumbnailUrl?: string;
}

/**
 * Represents a single blueprint file revision uploaded to the takeoff engine.
 */
export interface BlueprintRevision {
  id: string;
  projectId: string;
  name: string;               // e.g., "Structural Plans S1.0"
  versionLabel: string;       // e.g., "Rev A", "Rev 1", "Addendum 2"
  fileUrl: string;            // Original source PDF file path in storage
  fileSize: number;           // Size in bytes (to manage parsing limits)
  uploadedAt: string;
  status: 'processing' | 'ready' | 'failed';
  pages: BlueprintPage[];
  scale: BlueprintScale;
}

/**
 * 2D transformation variables generated by your 2-point similarity solver.
 * Used to align and overlay Revision B precisely on top of Revision A.
 */
export interface BlueprintAlignment {
  translateX: number;
  translateY: number;
  scale: number;
  rotationDeg: number;
}

/**
 * State configuration for active, screen-on-screen design file comparisons.
 */
export interface ComparisonState {
  /** The baseline blueprint page being compared against (typically Revision A rendered in Red) */
  basePageId: string | null;
  /** The incoming blueprint page being validated (typically Revision B rendered in Green) */
  comparePageId: string | null;
  /** Active transformation matrix applied to the compare canvas layer */
  alignment: BlueprintAlignment;
  /** Visually adjusts comparison layer visibility (0.0 = Hidden, 1.0 = Fully Opaque) */
  opacity: number;
  /** True when the visual comparison engine is rendering to the active viewport */
  isActive: boolean;
}

/**
 * Tracks viewport state globally for active session canvas caching.
 */
export interface ViewportState {
  zoom: number;
  offsetX: number;
  offsetY: number;
}